---
title: "Idea #1: Patient Matching for AML Treatment Development"
output:
  pdf_document: default
---

**Introduction:** Recognizing the unique genetic, molecular, and clinical characteristics of individual cancer manifestations, the treatment of cancer has recently moved away from a one-size-fits-all approach. This school of thought, referred to as personalized or precision medicine, has already to enhanced therapeutic responses, and ultimately increase overall survival in cancer patients. The goal of this project is to develop a framework for predicting patient response to cancer therapy, focusing on a blood cancer that accounts for about 1% of all cancer called Acute Myeloid Leukemia (AML), by matching patients with existing cancer cell lines based on the molecular characteristics of the disease. Cell lines are cheap and readily available to work with, so by matching patients with cell line that best mimics their disease, researchers could develop more specialized treatment regimens for AML.

**Methods:** The project will work off of datasets that are publicly available from Cbioportal.org. Three AML patient datasets have been identified for this project through Cbioportal.org, including studies conducted by OHSU in 2018 (672 samples) and 2022 (942 samples), as well as a pediatric AML study of 1025 samples (TARGET, 2018). These datasets contain a wealth of data on each patient. This includes detailed clinical data, as well as tumor sample genome and transcriptome sequencing. A cancer cell line dataset is available from a 2019 study from Broad which includes detailed clinical and sequencing information on 1,739 cancer cell lines, 48 of which are AML cell lines. A fair bit of work is needed to combine the datasets from these studies appropriately, to convert categorical variables to appropriate binary variable, etc.

In the initial stages, machine learning techniques will be applied for feature selection to identify key genetic factors and transcriptional elements influencing treatment outcomes. For patient-cell line matching, clustering algorithms will be employed to pair patients with appropriate AML cell lines -- currently exploring LASSO, Trees, PCA. The prediction of the impact of gene expression and mutation on AML patient survival will be explored using tree-based models -- an alternative approach with linear regression will also be considered.

**Implications:** The implications of this research extends to patients and their families, healthcare providers, and the cancer research community including the Robert's lab at Dickinson College which studies AML. The model's outcomes have the potential to guide and inform further research endeavors, contributing to the advancement of AML treatment strategies.

The major ethical considerations of this project are patient consent, data privacy, and the responsible utilization of predictive models in clinical settings. The data has been obtained through studies conducted at cancer research centers with informed consent and have been made publicly available. The application of a patient-cell line matching model presents no major ethical concerns. However, the model predicting overall survival could be misused or lead to patient harm if misapplied.