---
title: 'Idea #3'
output: pdf_document
---

**Introduction:** MedNews Week (MNW) serves as a pioneering free virtual educational platform designed to disseminate global medical education through biweekly programming, accessible on various social media platforms. At the forefront of MNW's offerings is the Keynote Conference, a flagship show that hosts live virtual presentations from esteemed leaders in oncology, providing the latest insights to a diverse global audience. As an organization, MNW is committed to bridging gaps in medical education by delivering high-quality information to traditionally underserved communities. Recognizing the extensive reach of our audience and the potential impact of MNW's programming, this project aims to conduct a comprehensive analysis to quantify and understand the influence of our initiatives.

**Methods:** To assess the impact and effectiveness of MNW's virtual educational initiatives, this project proposes the collection and analysis of data from Twitter, a prominent social media platform widely used for real-time communication and information dissemination. The project will involve systematic data collection from Twitter, focusing on user engagement, audience demographics, and the dissemination of MNW-related content. Hashtags, mentions, and interactions related to MNW and its Keynote Conference will be monitored to gauge the extent of social media activity and community engagement. An in-depth analysis of the demographics of MNW's Twitter audience will be conducted to understand the diversity and inclusivity of the platform. This includes factors such as geographical location, professional background, and language preferences. Building an understanding of who is driven to our platform and why is critical for developing future programming. Similarly, we are interested in how features (gender, institution, h-index, etc.) of the Keynote speaker impact lecture attendance and engagement. I think that two models should be trained, one would be a logistic regression predicting whether a Twitter account will attend a given Keynote Lecture, and two a linear regression (maybe a time series, since platform growth needs to be accounted for) to predict the number of attendees a given lecturer will draw. I would stick to simpler models to preserve interpretability. Some feature selection may also be necessary.

**Implications:** Understanding the impact of MNW's virtual educational initiatives on social media has significant implications for our organization. By gaining insights into audience demographics, sentiment, and content reach, MNW can tailor its programming to better meet the needs of diverse communities and enhance the effectiveness of medical education outreach. The findings from this project will inform strategic decisions, helping MNW further its mission of providing high-quality medical information to underserved populations and strengthening its position as a global leader in virtual medical education.